bug(fix): fix my sign in token [finishes #166008700]
Boths1229/quick-credit pull request #22
Opened 2019-05-14 19:32 UTC by Boths1229

#### What does this PR do?
- Implement my user sign in token

#### Description of the task to be completed?
- Remove token as part of requirement for user sign in. 

#### How can this manually be tested?
- clone this repo
```
$ git clone https://github.com/Boths1229/quick-credit.git
```
- install all dependencies
```
$ npm i
```
- start Application
```
$ npm start:dev
```
- log on to _localhost:<PORT>_ to interact with endpoint created

#### Any background context you want to provide?
> N/A
#### Relevant PT story(ies)
#166008700[https://www.pivotaltracker.com/n/projects/2326722]

#### Screenshots (if appropriate)
> N/A
#### Questions 
> N/A

[finishes #166008700]

2019-05-15 09:16 UTC, damafeez requested changes
Hi @Boths1229, you've done an awesome job altogether.
However, I don't think you commit message is detailed enough:
- the commit body should contain a breakdown (in steps) of how you have achieved the functionality in the commit header.

I think a commit message like this might be more appropriate
```
bug(authentication): remove token verification when signing in

- remove token requirement on sign-in
- update sign-in tests for conformity
- another thing I did
- yet another thing I did e.t.c

[finishes #166008700]
```
Also, your PR's title should not contain the footer `[finishes #166008700]`

Please attend/respond to the feedback

2019-05-15 09:16 UTC, damafeez commented on server/test/test.js
> +  const token = 'ajdsdkdk.akskks29030303umds.s';
You should remove this variable, YOU DON'T NEED A TOKEN WHEN SIGNING IN

2019-05-15 09:16 UTC, damafeez commented on server/test/test.js
>        .set('authorization', token)
You don't need to set authorisation token in the header while signing in.

2019-05-15 09:16 UTC, damafeez commented on server/test/test.js
>          expect(res.body).to.be.an('object');
You should check also that the returned object contains a token.

2019-05-15 09:20 UTC, Boths1229 commented on server/test/test.js
>        .set('authorization', token)
i did that.

2019-05-15 09:23 UTC, damafeez commented on server/test/test.js
>        .set('authorization', token)
You did?
Why are you passing token via the header in this test?

2019-05-16 22:44 UTC, damafeez requested changes
Great job implementing the suggested changes.
Please ensure your commits follow the recommended convention then you can merge.

You can modify your commit messages by doing `git commit --amend`

2019-05-16 23:27 UTC, merged